name=PIC16_Examples
version=1.1.0
author=Core PIC16
maintainer=Core PIC16
sentence=Ejemplos para el core PIC16F877A (JT40P).
paragraph=Blink, Serial, ADC, PWM, Servo, EEPROM, Interrupciones, I2C y LCD 16x2.
category=Other
url=
architectures=pic16
