#!/bin/zsh
# build_evidence.sh - Compila ejemplos en varios chips PIC y guarda la evidencia.
#
# Prueba que los cores compilan de verdad en distintos PIC16/PIC18 usando
# arduino-cli, y escribe un reporte en docs/BUILD_EVIDENCE.md con el tamanio
# de cada binario. Sirve como prueba reproducible para el repo.
#
# Requisitos: arduino-cli, los cores instalados en ~/Documents/Arduino/hardware/pic,
#             y MPLAB XC8. (Ver docs/INSTALL.md)
#
# Uso:  zsh tools/build_evidence.sh
#
# ---------------------------------------------------------------------------
set -u
SCRIPT_DIR="${0:A:h}"
REPO="${SCRIPT_DIR:h}"
OUT="$REPO/docs/BUILD_EVIDENCE.md"
LOGDIR="$REPO/docs/build_logs"
mkdir -p "$LOGDIR"

EX16="$HOME/Documents/Arduino/hardware/pic/pic16/libraries/PIC16_Examples/examples"

if ! command -v arduino-cli >/dev/null 2>&1; then
    echo "ERROR: arduino-cli no esta instalado." >&2
    exit 1
fi

# Lista de pruebas:  "FQBN|ruta_del_sketch|etiqueta"
typeset -a TESTS
TESTS=(
    "pic:pic16:jt40p|$EX16/01_Blink|Blink en PIC16F877A"
    "pic:pic16:jt40p|$EX16/02_SerialHello|Serial en PIC16F877A"
    "pic:pic16:jt40p|$EX16/11_LCD_I2C|LCD I2C en PIC16F877A"
    "pic:pic16:p16f887|$EX16/01_Blink|Blink en PIC16F887"
    "pic:pic16:p16f628a|$EX16/01_Blink|Blink en PIC16F628A"
    "pic:pic16:p16f690|$EX16/10_SoftwareSerial|SoftwareSerial en PIC16F690"
    "pic:pic18:p18f4550|$EX16/01_Blink|Blink en PIC18F4550"
    "pic:pic18:p18f2550|$EX16/02_SerialHello|Serial en PIC18F2550"
    "pic:pic18:p18f4620|$EX16/01_Blink|Blink en PIC18F4620"
)

{
  echo "# Build evidence / Evidencia de compilacion"
  echo ""
  echo "> Auto-generado por \`tools/build_evidence.sh\` el $(date '+%Y-%m-%d %H:%M')."
  echo "> Auto-generated by \`tools/build_evidence.sh\`."
  echo ""
  echo "Cada fila es un ejemplo real compilado con \`arduino-cli\` + XC8 para ese chip."
  echo "Each row is a real example compiled with \`arduino-cli\` + XC8 for that chip."
  echo ""
  echo "| Resultado / Result | Chip (FQBN) | Ejemplo / Example | Tamanio / Size |"
  echo "|:---:|---|---|---|"
} > "$OUT"

PASS=0; FAIL=0
for t in "${TESTS[@]}"; do
    fqbn="${t%%|*}"; rest="${t#*|}"
    sketch="${rest%%|*}"; label="${rest#*|}"
    logfile="$LOGDIR/$(echo "$fqbn" | tr ':' '_')_$(basename "$sketch").log"

    echo "Compilando: $label ($fqbn)..."
    if arduino-cli compile --fqbn "$fqbn" "$sketch" > "$logfile" 2>&1; then
        size=$(grep -oE 'Sketch uses [0-9]+ bytes \([0-9]+%\)' "$logfile" | head -1)
        [[ -z "$size" ]] && size="OK"
        echo "| ✅ | \`$fqbn\` | $label | $size |" >> "$OUT"
        PASS=$((PASS+1))
    else
        tail -3 "$logfile"
        echo "| ❌ | \`$fqbn\` | $label | ver log |" >> "$OUT"
        FAIL=$((FAIL+1))
    fi
done

{
  echo ""
  echo "**Total: $PASS OK, $FAIL fallidos / failed.**"
  echo ""
  echo "Logs completos en \`docs/build_logs/\`. / Full logs in \`docs/build_logs/\`."
} >> "$OUT"

echo ""
echo "=================================================="
echo "Evidencia escrita en: $OUT"
echo "Resultado: $PASS OK, $FAIL fallidos."
echo "=================================================="
[[ $FAIL -eq 0 ]]
